#!/usr/bin/env python3

###
# Reqs pkgs: xosd, alsa
###

from subprocess import run, Popen
import time
import os

BATTERY_LOW_THRESHOLD = 8
BATTERY_UP_THRESHOLD = 95
SHELL_CMD = [ "/usr/bin/osd_cat",
              "--align=center",
              "--pos=middle",
              "--font=-*-*-bold-*-*-*-96-120-*-*-*-*-*-*" ]
beep_path = os.path.expanduser('~/.dwm/scripts/bat_low_snd.wav')

def is_charging():
    with open("/sys/class/power_supply/BAT0/status") as f:
        return True if f.read().strip('\n') == "Charging" else False


def check_capacity():
    with open("/sys/class/power_supply/BAT0/capacity") as f:
        return int(f.read())


def extra_info():
    with open("/sys/class/power_supply/BAT0/energy_full") as f:
        energy_full = int(f.read())
    with open("/sys/class/power_supply/BAT0/energy_full_design") as f:
        energy_full_design = int(f.read())
    with open("/sys/class/power_supply/BAT0/cycle_count") as f:
        cycle_count = int(f.read())
    degradation = int(100 - (energy_full / energy_full_design * 100))
    return cycle_count, degradation


while True:
    delay_interval_sec = 60
    if check_capacity() <= BATTERY_LOW_THRESHOLD and not is_charging():
        run(['/usr/bin/aplay', '--device=pulse', beep_path], check=True)
        msg = f"!!BATTERY LOW. REMAINING {check_capacity()} %!!"
        proc = run(SHELL_CMD, input=msg, encoding="utf-8")
        delay_interval_sec = 0
    elif check_capacity() >= BATTERY_UP_THRESHOLD and is_charging():
        cycles, degradation = extra_info()
        msg = f"BATTERY CHARGED\nCycles: {cycles}\nDegradation: {degradation}%"
        proc = run(SHELL_CMD, input=msg, encoding="utf-8")
        delay_interval_sec = 0
    time.sleep(delay_interval_sec)

